export const data = {
  frontend: [
    "Astro",
    "bootstrap",
    "css",
    "html",
    "javascript",
    "jQuery",
    "nextjs",
    "react",
    "redux",
    "shadcn",
    "styled-components",
    "tailwind-css",
    "typescript",
    "zod",
  ],
  backend: [
    "apollo",
    "express-js",
    "GraphQL",
    "hono",
    "mysql",
    "node-js",
    "postgresql",
    "postman",
    "prisma",
    "rust",
  ],
  infrastructure: ["bun", "git", "Jest", "MongoDB", "mongoose", "neon", "supabase", "vite"],
};
